import React from 'react';
import LoginForm from "@/app/(public)/login/LoginForm";
import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Spring Shopping: Login",
    description: "Generated by create next app",
};
const LoginPage = () => {
    return <LoginForm />
};

export default LoginPage;
