import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "../globals.css";
import Providers from "@/components/common/Providers";
import {Toaster} from "sonner";
import {SidebarProvider} from "@/components/ui/sidebar";
import {AppSidebar} from "@/components/common/AppSidebar";
import AppHeader from "@/components/common/AppHeader";
import {ThemeProvider} from "next-themes";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Spring Shopping",
    description: "Generated by create next app",
};

export default function AdminLayout({
                                        children,
                                    }: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background relative z-10 flex min-h-svh flex-col overflow-hidden`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <Providers>
                <SidebarProvider>
                    <div className="flex min-h-screen w-screen">
                        <AppSidebar/>
                        <div className="flex-1 flex flex-col">
                            <AppHeader/>
                            <main className="p-4">
                                {children}
                                <Toaster richColors position="top-right"/>
                            </main>
                        </div>
                    </div>
                </SidebarProvider>
            </Providers>
        </ThemeProvider>

        </body>
        </html>
    );
}
